language: python
python:
- 3.5
install:
- pip install -e .
script:
- python setup.py test
deploy:
  provider: pypi
  user: jbooth
  password:
    secure: Ak2W04TcRCnK75hfst/GVRntLm3OGdlWdrvwNO3YcIE2beAVFHUox0c9ctVG4GVdSP7gAzxCRr1Kch1KyV4IqIeAu8KjzKfdaw2mFxFYOeCEbPAvfhSDtqLz4HcOjUwo8nwZ31mneSYQi38K8NOarXo+OZcViC1o6VNZNCXnnusCpty1hdqUrVmWESbSHquX+kdMHfApxeNESCp1Ks8KwThJ1emtoMXn2M8rDc5aSx02yGXpEYWuZBTil1N2ALguzcKJ30grQusDJd8NXBJrpO7hmfVq/tCiltH/4RiELA1NgSHyf9govYKSJklrF7bmeKCuGsAgHChAPfAe2jviyqrqS5pg+8dzUqmh8WnA6GdbCdKQBbTKOwWVSUZnYdEQHUY3wNUSDVflJy0B91XBslIbVvqPTp6l1pMrfqaJ3AuYnZXerR1ChmEth5tv0WdvPcsZMbVQ3XihuHHXpYoJRdpY3rxlLS3rt1F2Mqe/J4R8GttoCZAtqwH+4T80YSQgXDZlILrLXMLF6Flv4mBfznfiigFM0n416RUKf+13eSzdvDDVlCZh7PM9EcF81osd0A8J3L06bRacOAmpZyJ6c9eg1aWhn9MxWbAdd6unUTcpDsSXA/MNp+8PkSMKOy8hFZfncfV1k1FhkOZogUgh3Ykxh42JPEY7JfF9umB+7ag=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: svirpridon/pyrsnapshot
